// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestForge.Infrastructure.Data;

#nullable disable

namespace QuestForge.Infrastructure.Migrations
{
    [DbContext(typeof(QuestForgeContext))]
    partial class QuestForgeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("QuestForge.Core.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barbarian"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bard"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cleric"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fighter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ranger"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sorcerer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Wizard"
                        });
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Enemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerCharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("OwnerCharacterId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Weapon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Magic Weapon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Armor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Magic Armor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Magic Equipment"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tool"
                        });
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aasimar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dragonborn"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dwarf"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elf"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gnome"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Goliath"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Halfling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tiefling"
                        });
                });

            modelBuilder.Entity("QuestForge.Core.Entities.SubClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("SubSubClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "Path of the Berserker"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Path of the Wild Heart"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            Name = "Path of the World Tree"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            Name = "Path of the Zealot"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            Name = "College of Dance"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            Name = "College of Glamour"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            Name = "College of Lore"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 2,
                            Name = "College of Valor"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            Name = "Life Domain"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 3,
                            Name = "Light Domain"
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 3,
                            Name = "Trickery Domain"
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 3,
                            Name = "War Domain"
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 4,
                            Name = "Circle of the Land"
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 4,
                            Name = "Circle of the Moon"
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 4,
                            Name = "Circle of the Sea"
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 4,
                            Name = "Circle of the Stars"
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 5,
                            Name = "Battle Master"
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 5,
                            Name = "Champion"
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 5,
                            Name = "Eldritch Knight"
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 5,
                            Name = "Psi Warrior"
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 6,
                            Name = "Warrior of Mercy"
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 6,
                            Name = "Warrior of Shadow"
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 6,
                            Name = "Warrior of the Elements"
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 6,
                            Name = "Warrior of the Open Hand"
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 7,
                            Name = "Oath of Devotion"
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 7,
                            Name = "Oath of Glory"
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 7,
                            Name = "Oath of Ancients"
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 7,
                            Name = "Oath of Vengeans"
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 8,
                            Name = "Beast Master"
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 8,
                            Name = "Fey Wanderer"
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 8,
                            Name = "Gloom Stalker"
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 8,
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 9,
                            Name = "Arcane Trickster"
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 9,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 9,
                            Name = "Soulknife"
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 9,
                            Name = "Thief"
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 9,
                            Name = "Saboteur"
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 10,
                            Name = "Aberrant Sorcery"
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 10,
                            Name = "Clockwork Sorcery"
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 10,
                            Name = "Draconic Sorcery"
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 10,
                            Name = "Wild Magic Sorcery"
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 11,
                            Name = "Archfey Patron"
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 11,
                            Name = "Celestial Patron"
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 11,
                            Name = "Fiend Patron"
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 11,
                            Name = "Great Old One Patron"
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 11,
                            Name = "Hexblade"
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 12,
                            Name = "Abjurer"
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 12,
                            Name = "Diviner"
                        },
                        new
                        {
                            Id = 49,
                            ClassId = 12,
                            Name = "Evoker"
                        },
                        new
                        {
                            Id = 50,
                            ClassId = 12,
                            Name = "Illusionist"
                        });
                });

            modelBuilder.Entity("QuestForge.Core.Entities.SubSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("SubSpecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blue",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brass",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bronze",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Copper",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gold",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Green",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Red",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Silver",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "White",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Drow",
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "High Elf",
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wood Elf",
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 14,
                            Name = "Forest Gnome",
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rock Gnome",
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cloud Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 17,
                            Name = "Fire Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 18,
                            Name = "Frost Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 19,
                            Name = "Hill Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 20,
                            Name = "Stone Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 21,
                            Name = "Storm Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cloud Giant",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 23,
                            Name = "Abissal",
                            SpeciesId = 10
                        },
                        new
                        {
                            Id = 24,
                            Name = "Chthonic",
                            SpeciesId = 10
                        },
                        new
                        {
                            Id = 25,
                            Name = "Infernal",
                            SpeciesId = 10
                        });
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Character", b =>
                {
                    b.HasOne("QuestForge.Core.Entities.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestForge.Core.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestForge.Core.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Class");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Enemy", b =>
                {
                    b.HasOne("QuestForge.Core.Entities.Campaign", "Campaign")
                        .WithMany("Enemies")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Item", b =>
                {
                    b.HasOne("QuestForge.Core.Entities.Campaign", "Campaign")
                        .WithMany("Items")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestForge.Core.Entities.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuestForge.Core.Entities.Character", "OwnerCharacter")
                        .WithMany("Items")
                        .HasForeignKey("OwnerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("ItemType");

                    b.Navigation("OwnerCharacter");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Npc", b =>
                {
                    b.HasOne("QuestForge.Core.Entities.Campaign", "Campaign")
                        .WithMany("Npcs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.SubClass", b =>
                {
                    b.HasOne("QuestForge.Core.Entities.Class", "Class")
                        .WithMany("SubClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.SubSpecies", b =>
                {
                    b.HasOne("QuestForge.Core.Entities.Species", "Species")
                        .WithMany("SubSpecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Enemies");

                    b.Navigation("Items");

                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Character", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Class", b =>
                {
                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.ItemType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuestForge.Core.Entities.Species", b =>
                {
                    b.Navigation("SubSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
